# Generated by Django 4.2.2 on 2023-08-28 11:14

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_featured_post_img1_post_img2_post_img3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.upload_to_fotos),
        ),
        migrations.AlterField(
            model_name='post',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.upload_to_fotos),
        ),
        migrations.AlterField(
            model_name='post',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.upload_to_fotos),
        ),
        migrations.AlterField(
            model_name='post',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.upload_to_fotos),
        ),
    ]
