# Generated by Django 4.2.2 on 2024-01-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_gptprompt_title_gpt_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
